### ISSUE TITLE
Question about the pump and the gripper

### ISSUE THREAD

**Issue by hanghoo** [tinkrmind/programmable-air#7]
Hi @tinkrmind 
I am very interested in your vacuum air project. After seeing the video, I still have some question.
1. The gripper looks very powerful, so how do you make that? Do you fill some material inside?
2. You use 7 different pumps, why? How do you connect the pumps?
3. How much vacuum could you get?
4. How long does it take from work to stability?

**Comment by tinkrmind** [comment]
Hi Nick, thanks for the interest. You should know that this repository is only for archival purposes and I'm developing the project at github.com/programmable-air. Here are the answers to your questions:
1- The gripper is filled with coffee grounds.
2- I evaluated seven pumps, but finally settled on using the Pink-day-pump
3- The pump generates about -7.5PSI vacuum
4- Not sure I understand this question. Could you elaborate?

**Comment by hanghoo** [comment]
Hi Amitabh
Thanks for your reply soon.
The fourth question is that when the pumps start work and suck the air, how long does it take to pump out all air.

**Comment by tinkrmind** [comment]
Ah, it's maybe half a second.
